In [30]:
import os
import torch
import json
import csv
import argparse
import numpy as np
from PIL import Image
import torch.nn as nn
import multiprocessing
from utils import scores
from model import ResNet18
import torch.optim as optim
import torch.nn.functional as F
import matplotlib.pyplot as plt
from torchvision import datasets
import torchvision.models as models
from torch.autograd import Variable
import torch.backends.cudnn as cudnn
from config import args as default_args
from utils import DotDict, parse_arguments
import torchvision.transforms as transforms
from dataloader import CocoClassDatasetRandom

In [31]:
from config import args

In [32]:
def change_to_3_channel(x):
    if x.size()[0] == 1:
        return x.repeat(3, 1, 1)
    return x

train_transform = transforms.Compose([
                                    # transforms.Resize(size=(224,224)),
                                    # transforms.RandomCrop(224, padding=4),
                                    # transforms.RandomHorizontalFlip(), 
                                    transforms.ToTensor(),
                                    change_to_3_channel,
                                    transforms.Normalize(args.mean, args.std)
                                ])

val_transform = transforms.Compose([
    # transforms.Resize(size=(224,224)),
    transforms.ToTensor(),
    change_to_3_channel,
    transforms.Normalize(args.mean, args.std),
])

train_dataset = CocoClassDatasetRandom(images_path = args.train_images_path, annotation_path = args.train_annotation_path, transform = train_transform)
val_dataset = CocoClassDatasetRandom(images_path = args.val_images_path, annotation_path = args.val_annotation_path, transform = val_transform)

print(f'----> number of workers: {args.num_workers}')

loading annotations into memory...
Done (t=14.81s)
creating index...
index created!
loading annotations into memory...
Done (t=4.69s)
creating index...
index created!
----> number of workers: 40


In [33]:
batch_size = 4
trainloader = torch.utils.data.DataLoader(
    train_dataset, batch_size=batch_size, shuffle=True)
testloader = torch.utils.data.DataLoader(
    val_dataset, batch_size=batch_size, shuffle=False)

In [34]:
net = ResNet18() 
inp_features = net.linear.in_features
net.linear = torch.nn.Linear(in_features=inp_features, out_features=args.num_classes)

In [6]:
batch_x, batch_y = next(iter(trainloader))

print('-----> verify if model is run on random data')

-----> verify if model is run on random data


In [7]:
batch_x.shape, batch_y.shape

(torch.Size([4, 3, 224, 224]), torch.Size([4, 1, 40]))

In [8]:
outputs = net(batch_x)

print(f'Outputs shape: {outputs.shape}, batch labels shape: {batch_y.shape}') 

Outputs shape: torch.Size([4, 40]), batch labels shape: torch.Size([4, 1, 40])


In [9]:
criterion = nn.BCEWithLogitsLoss()
optimizer = optim.SGD(net.parameters(), lr = args.base_learning_rate, momentum=args.momentum, weight_decay=args.weight_decay)

In [10]:
print(f'Initial random loss: {criterion(outputs, batch_y.squeeze().float())}')

Initial random loss: 0.7147601842880249


In [11]:
batch_y.squeeze()

tensor([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0],
        [1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0]])

In [12]:
predicted = torch.round(torch.sigmoid(outputs))
predicted

tensor([[0., 0., 0., 1., 1., 0., 1., 0., 0., 1., 1., 0., 1., 1., 0., 1., 0., 0.,
         0., 0., 1., 1., 0., 1., 1., 1., 0., 0., 1., 0., 1., 1., 1., 0., 0., 1.,
         0., 0., 0., 0.],
        [0., 1., 0., 1., 1., 0., 1., 0., 0., 1., 0., 0., 1., 1., 0., 1., 0., 0.,
         0., 0., 1., 1., 0., 1., 1., 1., 0., 0., 1., 0., 1., 0., 1., 0., 0., 1.,
         0., 0., 0., 0.],
        [0., 1., 1., 1., 1., 0., 1., 0., 0., 0., 1., 0., 1., 1., 0., 1., 0., 1.,
         1., 0., 1., 1., 0., 1., 1., 1., 0., 1., 1., 0., 1., 0., 1., 1., 0., 1.,
         0., 0., 0., 0.],
        [0., 1., 0., 1., 1., 0., 1., 0., 0., 0., 1., 0., 1., 1., 0., 1., 0., 0.,
         0., 0., 1., 1., 0., 1., 1., 1., 0., 0., 1., 0., 1., 0., 1., 0., 0., 1.,
         0., 0., 0., 0.]], grad_fn=<RoundBackward0>)

In [13]:
predicted.eq(batch_y.squeeze().float())

tensor([[ True,  True,  True, False, False,  True, False,  True,  True, False,
         False,  True, False, False,  True, False,  True,  True,  True,  True,
         False, False,  True, False, False, False,  True,  True, False, False,
          True,  True, False,  True,  True, False,  True,  True,  True,  True],
        [False, False,  True, False, False, False, False,  True,  True, False,
          True,  True, False, False,  True, False,  True,  True,  True,  True,
         False, False,  True, False, False, False,  True,  True, False,  True,
         False,  True, False,  True,  True, False,  True,  True,  True,  True],
        [ True, False, False, False, False,  True, False,  True,  True,  True,
         False,  True, False, False,  True,  True,  True, False, False,  True,
         False, False,  True, False, False, False,  True, False, False,  True,
         False,  True, False, False,  True, False,  True,  True,  True,  True],
        [ True, False,  True, False, False,  True

In [14]:
correct = predicted.eq(batch_y.squeeze().float()).cpu().sum()
correct

tensor(85)

In [15]:
random_acc = correct/(batch_size * args.num_classes) * 100
print(f'Initial random acc: {random_acc} %')

Initial random acc: 53.125 %


In [22]:
AP, f1 = scores(batch_y.squeeze().numpy(), predicted.detach().numpy())

print(f'Initial AP score: {AP} %')
print(f'Initial f1 score: {f1} %')

Initial AP score: 0.0660341156664686 %
Initial f1 score: 0.09435817805383023 %


In [29]:
from sklearn.metrics import f1_score
f1_score(batch_y.squeeze().numpy(), predicted.detach().numpy(), average='samples')

0.09435817805383023

In [25]:
batch_y.squeeze().numpy(), predicted.detach().numpy()

(array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0],
        [1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0]]),
 array([[0., 0., 0., 1., 1., 0., 1., 0., 0., 1., 1., 0., 1., 1., 0., 1.,
         0., 0., 0., 0., 1., 1., 0., 1., 1., 1., 0., 0., 1., 0., 1., 1.,
         1., 0., 0., 1., 0., 0., 0., 0.],
        [0., 1., 0., 1., 1., 0., 1., 0., 0., 1., 0., 0., 1., 1., 0., 1.,
         0., 0., 0., 0., 1., 1., 0., 1., 1., 1., 0., 0., 1., 0., 1., 0.,
         1., 0., 0., 1., 0., 0., 0., 0.],
        [0., 1., 1., 1., 1., 0., 1., 0., 0., 0., 1., 0., 1., 1., 0